/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#define MASTER_RIGHT

#undef TAPPING_TERM
// Tap-hold configuration for home row mods.
#define TAPPING_TERM 170
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD
#define COMBO_COUNT 13

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4
#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 75
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 500
#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH (MOD_MASK_GUI)
#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 100
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 175
#define BILATERAL_COMBINATIONS_TYPING_STREAK_MODMASK (~(MOD_MASK_SHIFT|MOD_MASK_ALT))
